authors = ["Andrey Zakharevich <andreyzakharevich@gmail.com>"]
name = "NDPriorityQueues"
uuid = "62ce6dcf-afc2-4b9e-bf6a-7a1353c578d1"
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
DataStructures = "0.18"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
